name: intentclassifier
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - black==23.9.1
      - isort==5.12.0
      - ruff==0.1.8
      - pre-commit==3.4.0
      - pytest==7.4.3
