[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_pary = ["models", "pipeline", "processors", "utils", "scripts", "managers"]
[tool.ruff]
line-length = 88
# E: pycodestyle(에러), F: pyflakes, W: 경고, I: import 정렬 검사
select = ["E", "F", "W"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]
